function z = f2D(x,y)
% function used for the 2D test
    
    z = (...
            sin(    x(1,:).*cos(    x(1,:).*y   )  )   +   ...
            cos(    x(2,:).*sin(x(2,:).*y) - sin(x(1,:).*x(2,:))  )...
        ).*exp(0.5*(x(1,:)-2).^2+0.5*(x(2,:)-2).^2);
end